os:
  - linux

dist: trusty
sudo: false
language: node_js

node_js:
  - '10'
  - '8'
  - '9'

cache:
  yarn: true

jobs:
  include:
    - stage: test
      install:
        - yarn
      script:
        - yarn test

    - stage: "[example] remote image attachments"
      before_install:
        - cd examples/recipes-with-photos
      install:
        - yarn
      script:
        - yarn build
