os:
  - linux

dist: trusty
sudo: false
language: node_js

cache:
  yarn: true

matrix:
  include:
    - name: 'Node Current'
      node_js: 'node'
    - name: 'Node LTS'
      node_js: 'lts/*'

jobs:
  include:
    - stage: test
      install:
        - yarn
      script:
        - yarn test
    - stage: "[example] remote image attachments"
      before_install:
        - cd examples/recipes-with-photos
      install:
        - yarn
      script:
        - yarn build
