os:
  - linux

dist: trusty
sudo: false
language: node_js

cache:
  yarn: true

jobs:
  include:
    - &test
      stage: test
      install:
        - yarn
      script:
        - yarn test
    - <<: *test
      node_js: 'node'
    - &examplephoto
      stage: "[example] remote image attachments"
      before_install:
        - cd examples/recipes-with-photos
      install:
        - yarn
      script:
        - yarn build
    - <<: *examplephoto
      node_js: 'node'
