os:
  - linux

dist: trusty
sudo: required

jobs:
    include:
        - stage: build and test
          language: node_js
          node_js:
            - '8'
            - '9'
            - '10'
          cache:
            yarn: true
          install:
            - yarn
          script:
            - yarn test

        - stage: example remote image attachments
          language: node_js
          node_js:
            - '8'
            - '9'
            - '10'
          cache:
            yarn: true
          before_install:
            - cd examples/recipes-with-photos
          install:
            - yarn
          script:
            - yarn build
