os:
  - linux

dist: trusty
sudo: false
language: node_js

matrix:
  include:
    - node_js: '10'
    - node_js: '8'
    - node_js: '9'

cache:
  yarn: true

jobs:
  include:
    - stage: test
      install:
        - yarn
      script:
        - yarn test
    - stage: "[example] remote image attachments"
      before_install:
        - cd examples/recipes-with-photos
      install:
        - yarn
      script:
        - yarn build
